version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: payment
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: paymentpw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - payment-network

  axon-server:
    image: axoniq/axonserver:latest
    container_name: axon-server
    restart: always
    ports:
      - "8024:8024" # Web UI
      - "8124:8124" # Axon Server connection
    volumes:
      - axonserver_data:/data
      - axonserver_events:/events
    networks:
      - payment-network

volumes:
  postgres_data:
  axonserver_data:
  axonserver_events:

networks:
  payment-network:
    driver: bridge