version: '3.8'

services:
  app:
    image: openjdk:21
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/payment
      - SPRING_DATASOURCE_USERNAME=payment
      - SPRING_DATASOURCE_PASSWORD=paymentpw
    stdin_open: true
    tty: true

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: payment
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: paymentpw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: